on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  x:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cargo clippy
    - run: cargo fmt --check
    - run: sudo apt install -y gcc-aarch64-linux-gnu
    - run: rustup target add aarch64-unknown-linux-gnu
    - run: mkdir -p ~/.cargo
    - run: |
        cat <<EOF >~/.cargo/config.toml
        [target.aarch64-unknown-linux-gnu]
        linker = "aarch64-linux-gnu-gcc"
        EOF
    - run: cargo build --release --target aarch64-unknown-linux-gnu
    - uses: actions/upload-artifact@v4
      with:
        name: rpi-zero-usb-iso
        path: target/aarch64-unknown-linux-gnu/release/rpi-zero-usb-iso
    - run: gh release create --generate-notes -t "Release $(date "+%Y-%m-%d_%H%M")" release_$(date "+%Y-%m-%d_%H%M") target/aarch64-unknown-linux-gnu/release/rpi-zero-usb-iso
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
